name: Trigger build

on:
  push:
    branches: ['master', 'develop', 'main', 'dev']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'pull_request'
        run: gh pr checkout ${{ github.event.pull_request.number }}
      - name: Trigger build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "quynh.nguyen@digitalfortress.dev"
          git config user.name "Quynh-Nguyen"
          git commit --allow-empty -m "Trigger Build"
          git push
